/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import com.mycompany.proyecto1edd.Almacen;
import com.mycompany.proyecto1edd.Lista;
import com.mycompany.proyecto1edd.ManejoArchivo;
import com.mycompany.proyecto1edd.Nodo;
import com.mycompany.proyecto1edd.grafo.Grafo;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author davidmizrahi
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    private Lista<String> producto;
    private char idOrigen;
    private char idLlegada;
    private int peso;
    private Grafo grafo;

    /**
     *
     */
    public Interfaz() {
        this.producto = new Lista();
        this.idOrigen = ' ';
        this.idLlegada = ' ';
        grafo = new Grafo();
        this.peso = 0;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        file = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        agregarAlmacen = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idAlmacen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        file.setText("Elegir Archivo");
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });
        jPanel1.add(file, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        agregarAlmacen.setText("Agregar Almacen");
        agregarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(agregarAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jTextField2.setText("Para agregar un almacen inserte un id y una lista de productos:");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 430, 30));

        jLabel1.setText("Id almacen");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        idAlmacen.setText("Inserte id de (origen, llegada)");
        idAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(idAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel2.setText("Lista Productos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        jTextField3.setText("Inserte productos");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jLabel3.setText("Peso Arista");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jTextField4.setText("Inserte peso de la arista");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fc =  new JFileChooser();
        
        int seleccion = fc.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION){
        
            File fichero = fc.getSelectedFile();
            
            this.jTextField1.setText(fichero.getAbsolutePath());
            
            try(FileReader fr = new FileReader(fichero)){
            
                String cadena = "";
                int valor = fr.read();
                
                while (valor != -1){
                
                    cadena = cadena + (char) valor;
                    
                    valor = fr.read();
                }
                this.jTextArea1.setText(cadena);
                
                JOptionPane.showMessageDialog(null,"Se ha cargado correctamente el archivo.");
                
            
            }catch(IOException e){
            
                e.printStackTrace();
            }
            
        }
        
        
    }//GEN-LAST:event_fileActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void agregarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAlmacenActionPerformed
        // TODO add your handling code here:
         
       
            try (FileWriter f = new FileWriter("/Users/davidmizrahi/NetBeansProjects/proyecto1EDD_5-05/amazon.txt", true); 
                    BufferedWriter b = new BufferedWriter(f); 
                    PrintWriter p = new PrintWriter(b);) {
                

            //PrintWriter pw = new PrintWriter("/Users/davidmizrahi/NetBeansProjects/proyecto1EDD_5-05/amazon.txt");
            
            
        //ManejoArchivo.leerArchivo(f, grafo);

        //JOptionPane.showMessageDialog(null, "Se ha agregado el almacen correctamente.");

        String id = idAlmacen.getText().toUpperCase();
                System.out.println(idAlmacen.getText());

        Character idOrigen = id.charAt(0);
        Character idLlegada = id.charAt(2);
        
        p.println(idOrigen + "," + idLlegada + "," + jTextField4.getText() );
        
        System.out.println("Prueba");

        //JOptionPane.showMessageDialog(null, "Se ha agregado el almacen correctamente.");

        
        peso = Integer.parseInt(jTextField4.getText());
        
        Almacen almacen = new Almacen(idOrigen);
                System.out.println("Prueba 1");
        almacen.setProductos(producto);
        System.out.println("Prueba 2");

                //Grafo grafo;
        grafo.insertarAlmacen(almacen);

        //grafo.insertarArista(almacen.getId(), idLlegada, peso);
        //grafo.insertarAlmacen(almacen);
        
        JOptionPane.showMessageDialog(null, "Se ha agregado el almacen correctamente.");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
            catch(IOException e){
                e.printStackTrace();
            }

//        ManejoArchivo.leerArchivo(file, grafo);
//
//        
//        String id = idAlmacen.getText().toUpperCase();
//        Character idOrigen = id.charAt(0);
//        
//        Character idLlegada = id.charAt(2);
//        
//        int pesoArista = Integer.parseInt(jTextField4.getText());
//        
//        Almacen almacen = new Almacen(idOrigen);
//        almacen.setProductos(producto);
//        
//                //Grafo grafo;
//        grafo.insertarArista(almacen.getId(), idLlegada, pesoArista);
//        
//        grafo.insertarAlmacen(almacen);
//        
//        JOptionPane.showMessageDialog(null, "Se ha agregado el almacen correctamente.");

        
//String list = input2.getText().replace(",", "");

//       Graphics graph;
        
    }//GEN-LAST:event_agregarAlmacenActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void idAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAlmacenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idAlmacenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int num = 0;
        String s = jTextField3.getText();
        char[] gfg = s.toCharArray();
        for (int i = 0; i < gfg.length; i++) {
            if(gfg[i] == ' '){
            
                JOptionPane.showMessageDialog(null, "ERROR: Recuerde no dejar espacios al introducir productos");
            }
        }
    
        String list = jTextField3.getText();
        
        String[] arregloProd = list.split(",");
        //Lista<String> producto = new Lista<>();
        
        
        for (int i = 0; i < arregloProd.length; i++) {
            
            producto.agregarElemento(arregloProd[i]);
            
        }
        //producto.imprimirValores();
        Nodo aux = producto.getpFirst();

        String string = "";
        while (aux != null) {
            
            
             string = string + String.valueOf(aux.getInfo()) + ",";
            
            aux = aux.getpNext();

            
        }
        
        JOptionPane.showMessageDialog(null, "Se ha agregado la lista de productos.");

        JOptionPane.showMessageDialog(null, string);
        

        //productos.agregarElemento(list);
        //JOptionPane.showMessageDialog(null, productos.imprimirValores());

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Grafo grafo;
//        for (int i = 0; i < grafo.getAristas().length; i++) {
//            System.out.println("epale");
//            for (int j = 0; j < grafo.getAristas()[i].length; j++) {
//                System.out.println("no silbe");
                 //if(idAlmacen.getText().charAt(2) == grafo.getAristas()[i][j]){
                     //System.out.println("no silbe na")//;
                    Character idOrigen = idAlmacen.getText().charAt(0);
                    Character idLlegada = idAlmacen.getText().charAt(2);
                    System.out.println(idOrigen.charValue());
        if(idAlmacen.getText().length() > 3){
        
            JOptionPane.showMessageDialog(null, "ERROR: Recuerde introducir (Almacen Origen,Almacen Llegada)");
        }
        //idAlmacen.setText("");
        
        //else{JOptionPane.showMessageDialog(null, "ERROR: No se permite la existencia de vertices aislados, " + idLlegada + " no se encuentra en el grafo");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         peso = Integer.parseInt(jTextField4.getText());
        //jTextField4.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAlmacen;
    private javax.swing.JButton file;
    private javax.swing.JTextField idAlmacen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
